theme: dinky
title: The Ecletic Reader
description: A place to share with you my love of reading and my thoughts on the books read
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
